[general]
live_config_reload = true
import = ["~/.config/alacritty/themes/gruvbox.toml"] 

[window]
decorations = "Buttonless"
opacity =  0.95
startup_mode = "SimpleFullScreen"
padding = { x = 5, y = 5 }

[font]
normal = { family = "MesloLGS NF", style  = "Regular" }
bold = { family = "MesloLGS NF", style  = "Bold" }
italic = { family = "MesloLGS NF", style  = "Italic" }
size = 14

[mouse]
hide_when_typing = true

[cursor]
style = "Block"
unfocused_hollow = false

[env]
TERM = "xterm-256color"
